# Site settings
title: Mental's Blog
SEOTitle: Mental's Blog | 万事胜意
header-img: img/background.jpg
email: mental2008@163.com
description: "ACMer/SCUTer"
keyword: "mental2008"
# your host, for absolute URL
url: "https://blog.lingyunyang.com"
# for example, '/blog' if your blog hosted on 'host/blog'
baseurl: ""

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
weibo_username:     3614037533
zhihu_username:     mental2008
github_username:    mental2008
twitter_username:   stephenyang1999
facebook_username:  100015012043418
linkedin_username:  stephenyang1999

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: Asia/Shanghai

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins:
  - jekyll-paginate
  - jekyll-feed

# feed
feed:
  path: feed.xml
  posts_limit: 19270817 # unlimited

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: mental2008

# Netease settings
# netease_comment: false

# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'G-8YVSXN5NVF'

# Sidebar settings
# whether or not using Sidebar.
sidebar: true
sidebar-about-description: "Winter is coming<br>一如既往，万事胜意"
# use absolute URL, seeing it's used in both `/` and `/about/`
sidebar-avatar: /img/tohsaka_rin.png

# Featured Tags
# whether or not using Feature-Tags
featured-tags: true
# A tag will be featured if the size of it is more than this condition value
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true

# Friends
friends: [
    {
        title: "icepoint",
        href: "https://icepoint666.github.io/"
    }
]
